commerce_installments.installment_type.*:
  type: config_entity
  label: 'Installment type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    workflow:
      type: string
      label: 'Workflow'
