commerce_installments.installment_plan_type.*:
  type: config_entity
  label: 'Installment Plan type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
