commerce_installments.installment_plan_methods.*:
  type: config_entity
  label: 'Installment Plan Method config'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: commerce_installments.installment_plan_methods.plugin.[%parent.plugin]
    conditions:
      type: sequence
      sequence:
        type: commerce_condition
    uuid:
      type: string

commerce_installments.installment_plan_methods.plugin.*:
  type: commerce_installments.installment_plan_methods_configuration

commerce_installments.installment_plan_methods_configuration:
  type: mapping
  mapping:
    installment_plan_bundle:
      type: string
      label: 'Installment Plan Bundle'
    installment_bundle:
      type: string
      label: 'Installment Bundle'
    number_payments:
      type: sequence
      label: 'Number of payments'
      sequence:
        - type: integer
    time_of_day:
      type: string
      label: 'Time of day to execute payment'
    day:
      type: string
      label: 'Day of month'
    timezone:
      type: string
      label: 'Timezone to execute payment'
